<CustomButton@Button>
    font_size: 32
    color: 155, 32, 255, 1
    size: 150, 50
    background_normal: ''
    background_down: 'black.jpg'
    background_color: 0.88, 0.88, 0.88, 1

<CustomWidget>:
    CustomButton:
        text: 'root.x, 200'
        pos: root.x, 200

    CustomButton:
        text: '200, 200'
        pos: 200, 200

    CustomButton:
        text: '200, root.y'
        pos: 200, root.y